athletes:
  - name: "Мира Георгиева"
    intervals_id: "i333802"
    world_triathlon_id: "178014"
    telegram_alias: "mira"
    sport: "cycling"
  - name: "Миролюба Ненкова"
    intervals_id: "i273532"
    world_triathlon_id: "188676"
    telegram_alias: "mirolyuba"
    sport: "cycling"
  - name: "Симеон Бобеков"
    intervals_id: "i172547"
    world_triathlon_id: "181219"
    telegram_alias: "simeon"
    sport: "cycling"
